spring.application.name=apisandovalescloud
# ==========================
# Server
# ==========================
server.port=8084

# ==========================
# Multipart
# ==========================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=2048MB
spring.servlet.multipart.max-request-size=2048MB

# ==========================
# HomeDrive Storage
# ==========================
# Ruta base donde se guardarán TODOS los archivos.
# Puede cambiarse mediante la variable de entorno HOMEDRIVE_ROOT.
# Windows: C:/HomeDrive
# Linux/Mac: /home/usuario/HomeDrive
homedrive.root-dir=${HOMEDRIVE_ROOT:./cloud}

# ==========================
# Logging
# ==========================
logging.level.com.homedrive=INFO

